Reviews/__init__.py
from flask import current_app, Flask, redirect, url_for

def create_app(config):
    """
    Creates and returns app using flask app factory model.
    """
    app = Flask(__name__)
    app.config.from_object(config)

    # Setup the data model.
    with app.app_context():
        model = get_model()

    # Register the Movie Reviews blueprint.
    from .views import views
    app.register_blueprint(views)

    @app.route("/")
    def index():
        language = 'en'
        return redirect(url_for('views.main', language=language))

    return app


def get_model():
    """
    Imports and returns datastore model.
    """
    model_backend = current_app.config['DATA_BACKEND']
    if model_backend == 'datastore':
        from . import model_datastore
        model = model_datastore
    else:
        raise ValueError("No appropriate databackend configured. ")

    return model

Reviews/views.py
#!/usr/bin/env python3
# Copyright (c) 2018 Jeff Lund, Kevin Young
"""
Movie review flask app
"""

from flask import Flask, redirect, request, url_for, render_template, current_app, Blueprint
from Reviews import get_model
from .talktome import read_text
from .translate import translate_text, translate_list
from google.cloud import storage

views = Blueprint('views', __name__)

@views.route('/<language>', methods=['GET', 'POST'])
@views.route('/index/<language>', methods=['GET', 'POST'])
def main(language):
  """
  Renders landing page for movie review site. POST request changes language setting 
  and redirects back to the index page to update the displayed language within.
  """
  # Creates a list of the html page text and translates it for use in the index page.
  pageText = ['Ripe Tomatoes', 'Welcome to Ripe Tomatoes', 'A fresher movie review site', 'Please select the review language',
  	'English', 'French', 'Italian', 'Korean', 'Spanish', 'Turkish', 'Submit', 'Current language is', 
    'Movie Reviews', 'Add Movie Reviews']
  pageTranslation = translate_list(pageText, language)

  if request.method == 'POST':
     # Sets the language variable to the desired displayed language and speech.
     language = request.form['review_lang']
     return redirect(url_for('views.main', language=language))

  return render_template('index.html', lang=full_language(language), text=pageTranslation, language=language)

@views.route('/reviews/<language>', methods=['GET', 'POST'])
def reviews(language):
  """
  Renders all reviews from the model.
  POST request redirects to synth page where an audio element plays the spoken text of the selected review.
  """
  # Databases returned in tuple (Movie, Review).
  # Must be unpacked before use in render template.
  model = get_model()
  dbs = model.select(language)
  if dbs is None:
      dbs = [[],[]]
  movies = dbs[0]
  reviews = dbs[1]
  if request.method == 'POST':
      text = 'placeholder'
      id = int(request.form['synth'])
      # Find text associated with review id.
      for row in reviews.values():
          for list_element in row:
              if id == list_element['id']:
                  text = list_element['review']
      filename = read_text(text, language)
      return redirect(url_for('views.synth', filename=filename, language=language))

  # Creates a list of the html page text and translates it for use in the reviews page.
  pageText = ['Ripe Tomatoes', 'Movie Reviews!', 'Main Page', 'Add Movie Review', 'Directed By', 'Released', 'Rating', 'Runtime',
  	'minutes', 'Genre', 'Rating', 'Author']
  pageTranslation = translate_list(pageText, language)

  return render_template('reviews.html', movies=movies, reviews=reviews, text=pageTranslation, language=language)

@views.route('/submit/<language>', methods=['GET', 'POST'])
def submit(language):
  """
  Renders submission form to submit a new movie review.
  """
  # Creates a list of the html page text and translates it for use in the submit page.
  pageText = ['Ripe Tomatoes', 'Name of Movie', 'Released', 'Year', 'Director', 'Movie Rated', 'Not Rated',
  	'Runtime', 'minutes', 'Genres', 'Write your review here', 'Rating', 'Reviewed by',
  	'Submit Review', 'Main Page']

  # Defines available genres for the movie. Makes list available in GET and POST.
  genres = ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', \
    'Documentary', 'Drama', 'Family', 'Fantasy', 'Film Noir', 'History', 'Horror', \
    'Indie','Music', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Short', 'Sport', \
    'Superhero', 'Thiller', 'War', 'Western']
  pageTranslation = translate_list(pageText, language)
  genresTranslation = translate_list(genres, language)

  if request.method == 'POST':
    model = get_model()
    genre_selected = [gen for gen in genres if gen in request.form]
    model.insert(request.form['mov_name'], request.form['release_year'], \
      request.form['director'], request.form['mov_rating'], \
      request.form['runtime'], ','.join(genre_selected), request.form['review'], \
      request.form['rev_name'], request.form['rev_rating'])

    return redirect(url_for('views.reviews', language=language))

  return render_template('submit.html', genres=genresTranslation, text=pageTranslation, language=language)

@views.route('/synth/<filename>/<language>')
def synth(filename, language):
    """
    Loads a given mp3 file from storage bucket to HTML5 audio element. 
    Used to play audio reviews generated from Text-to-Speech API.
    """
    bucket = storage.Client().get_bucket(current_app.config['STORAGE'])
    blob = bucket.get_blob(filename)
    audio = blob.public_url

    # Creates a list of the html page text and translates it for use in the synth page.
    pageText = ['Ripe Tomatoes', 'Your browser does not support the audio element.', 'Movie Reviews']
    pageTranslation = translate_list(pageText, language)

    return render_template('synth.html', audio=audio, text=pageTranslation, language=language)

def full_language(language):
  """ 
  Takes the language variable and returns the full language text. 
  """
  lang = {'en': 'English', 'es': 'Spanish', 'it' : 'Italian', 'fr': 'French', 'tr': 'Turkish', 'ko': 'Korean'}
  return  translate_text(lang[language], language)

Reviews/templates/base.html
<!doctype html>
<html>
  <head>
        <link href='https://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet'>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="icon" href="data:,">
    <title>
      {% block title %} {% endblock %} - Ripe Tomatoes
    </title>
  </head>
  {% block header %}
  <div class="header">
    <a href="{{ url_for('views.main', language=language) }}">{{ text[0] }}</a>
  </div>
  {% endblock %}
  <div class="body">
    {% block content %}{% endblock content %}
  </div>
</html>

Reviews/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block content %}
<center>
  <h1>{{ text[1] }}</h1>
  <h3>{{ text[2] }}</h3>
  <br>
  <h4>{{ text[3] }}</h4>
  <form method="POST" action="">
    <select name="review_lang">
      <option value="en">{{ text[4] }}</option>
      <option value="fr">{{ text[5] }}</option>
      <option value="it">{{ text[6] }}</option>
      <option value="ko">{{ text[7] }}</option>
      <option value="es">{{ text[8] }}</option>
      <option value="tr">{{ text[9] }}</option>
    </select>
    <button onMouseOver="this.style.backgroundColor='#8eb190'" onMouseOut="this.style.backgroundColor='#4CAF50'" type="submit" 
    style="background-color:#4CAF50; color:white;">{{ text[10] }}</button>
  </form>
  <h4>{{ text[11] }}: {{ lang }}</h4>
  <br>
  <form>
 	<button onMouseOver="this.style.backgroundColor='#856E9B'" onMouseOut="this.style.backgroundColor='#4d0099'" type="submit" formaction="{{ url_for('views.reviews', language=language) }}" 
 	style="background-color:#4d0099; color:white; border-radius: 6px; padding-left: 1.5em; padding-right: 1.5em;">{{ text[12] }}</button>
  	<button onMouseOver="this.style.backgroundColor='#89B0BD'" onMouseOut="this.style.backgroundColor='#008CBA'" type="submit" formaction="{{ url_for('views.submit', language=language) }}"
  	style="background-color:#008CBA; color:white; border-radius: 6px;" >{{ text[13] }}</button>
  </form>
</center>
{% endblock %}

Reviews/templates/reviews.html
{% extends "base.html" %}
{% block title %} Reviews {% endblock %}
{% block content %}
<center class="logo">{{text[1]}}</center>
<center>
  <form>
  	<button onMouseOver="this.style.backgroundColor='#856E9B'" onMouseOut="this.style.backgroundColor='#4d0099'" type="submit" formaction="{{ url_for('views.main', language=language) }}" 
  	style="background-color:#4d0099; color:white; border-radius: 6px; padding-left: 2.6em; padding-right: 2.6em;">{{ text[2] }}</button>
  	<button onMouseOver="this.style.backgroundColor='#89B0BD'" onMouseOut="this.style.backgroundColor='#008CBA'" type="submit" formaction="{{ url_for('views.submit', language=language) }}" 
  	style="background-color:#008CBA; color:white; border-radius: 6px;">{{ text[3] }}</button>
  </form>
</center>
{% for movie in movies %}
<div class="card">
  <h1>{{ movie }}</h1>
  {{ text[4] }}: {{ movies[movie]['director']}}<br>
  {{ text[5] }}: {{ movies[movie]['release_year'] }}<br>
  {{ text[6] }}: {{ movies[movie]['mov_rating'] }}<br>
  {{ text[7] }}: {{ movies[movie]['runtime'] }} {{ text[8] }}<br>
  {{ text[9] }}: {{ ', '.join(movies[movie]['genre']) }} <br><br>
  {% for review in reviews[movie] %}
  <div class="ele">
    <form method="POST">
	    <button class="microphone" type=submit name="synth" value={{ review['id'] }}><i style="background-color: inherit;" class="fa fa-microphone"></i></button>
    </form><br>
      {{ review['review'] }}<br><br>
    {{ text[10] }}: {{ review['rev_rating'] }}/5<br>
    {{ text[11] }}: {{ review['rev_name'] }}<br>

  </div>
  {% endfor %}
</div>
{% endfor %}
<br>
{% endblock %}

Reviews/templates/submit.html
{% extends "base.html" %}
{% block title %} Submit New Review {% endblock %}
{% block content %}
<table class="card">
  <form method="POST">
    <tr>
      <td><label for="mov_name">{{ text[1] }}: </label></td>
      <td><input class="entry_field" type="text" name="mov_name" required></td>
    </tr>
    <tr>
    <td><label for="release_year">{{ text[2] }} ({{ text[3] }}): </label></td>
    <td><input class="entry_field" type="number" name="release_year" min="1895" max="2018" required></td>
  </tr>
  <tr>
    <td><label for="director">{{ text[4] }}: </label></td>
    <td><input class="entry_field" type="text" name="director" required></td>
  </tr>
  <tr>
    <td><label for="mov_rating">{{ text[5] }}: </label></td>
    <td>
      <input type="radio" name="mov_rating" value="G">G
      <input type="radio" name="mov_rating" value="PG">PG
      <input type="radio" name="mov_rating" value="PG-13" checked>PG-13
      <input type="radio" name="mov_rating" value="R">R
      <input type="radio" name="mov_rating" value="NC-17">NC-17
      <input type="radio" name="mov_rating" value="Not Rated">{{ text[6] }}
    </td>
  </tr>
  <tr>
    <td><label for="runtime">{{ text[7] }} ({{ text[8] }}): </label></td>
    <td><input class="entry_field" type="number" name="runtime" required></td>
    </tr>
    <tr>
      <td><label for="genre"> {{ text[9] }}: </label></td>
      <td>{% for g in genres %}
        <input type="checkbox" name="{{ g }}"> {{ g }}
        {% endfor %}
      </td>
    </tr>
    <tr>
      <td colspan="4"><textarea name="review" rows="20" cols="40" placeholder="{{ text[10] }}" required></textarea></td>
    </tr>
    <tr>
      <td><label for="rev_rating">{{ text[11] }}: </label></td>
      <td>
        <input type="radio" name="rev_rating" value=1>1
        <input type="radio" name="rev_rating" value=2>2
        <input type="radio" name="rev_rating" value=3>3
        <input type="radio" name="rev_rating" value=4>4
        <input type="radio" name="rev_rating" value=5 checked>5
      </td>
    </tr>
    <tr>
      <td><label for="rev_name">{{ text[12] }}: </label></td>
      <td><input class="entry_field" type="text" name="rev_name" required></td>
    </tr>
    <tr><td>
      <button onMouseOver="this.style.backgroundColor='#89B0BD'" onMouseOut="this.style.backgroundColor='#008CBA'" type="submit" 
      style="background-color:#008CBA; color:white; border-radius: 6px; padding-left: 1.6em; padding-right: 1.6em;">{{ text[13] }}</button></td></tr>
    </form>

    </table>
    <br>
    <center>
    	<form>
    		<button onMouseOver="this.style.backgroundColor='#856E9B'" onMouseOut="this.style.backgroundColor='#4d0099'" type="submit" formaction="{{ url_for('views.main', language=language) }}" 
    		style="background-color:#4d0099; color:white; border-radius: 6px; padding-left: 2.6em; padding-right: 2.6em;">{{ text[14] }}</button>
    	</form>
    </center>

  {% endblock %}

Reviews/templates/synth.html
{% extends "base.html" %}
{% block title %} Reading Rainbow {% endblock %}
{% block content %}
<center>
  <br>
  <audio controls>
    <source src="{{ audio }}" type="audio/mp3">
      {{ text[1] }}
  </audio>
  <br>
  <br>
  <br>
  <form>
    <button onMouseOver="this.style.backgroundColor='#856E9B'" onMouseOut="this.style.backgroundColor='#4d0099'" type="submit" formaction="{{ url_for('views.reviews', language=language) }}" 
    style="background-color:#4d0099; color:white; border-radius: 6px; padding-left: 1.5em; padding-right: 1.5em;">{{ text[2] }}</button>
  </form>
</center>
{% endblock %}